### ISSUE TITLE
New Project Dialog templates search provider

### ISSUE THREAD

**Issue by gundermanc** [gundermanc/VSOmniBox#15]
- Enable search of New Project dialog templates from the search box.

**Comment by gundermanc** [comment]
@joyceliang will be looking at this.

**Comment by JoyceLiang** [comment]
@gundermanc I've done the initiate version for project template search, checked it in master.

**Comment by gundermanc** [comment]
Thanks! Looks like with the change, quick launch and go to no longer return results. Lets take a look tomorrow and see if we can get everything playing nicely together.

**Comment by gundermanc** [comment]
Also can we try and expand this to allow searching of item templates as well (classes, files, etc) :)
